use_frameworks!

target 'RichAPM_Example' do
  pod 'RichAPM', :path => '../'

  target 'RichAPM_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
